# Generated by Django 3.1.2 on 2020-11-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dashboard', '0002_auto_20201102_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_com', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
    ]
